version: '3.9'

services:
  qitpy:
    container_name: qitpy_release
    build:
      context: .
      dockerfile: Dockerfile.deploy
    restart: unless-stopped
    expose:
      - 80
    networks:
      - qitpy-proxy_qitpy-proxy

networks:
  qitpy-proxy_qitpy-proxy:
    external: true